app:
  name: sale-service
  mode: debug

mysql:
  host: "127.0.0.1"
  port: "3306"
  driverName: mysql
  username: root
  password: ""
  database: sale

agent:
  appId: weixin
  appSecret: grSDG234

redis:
  host: localhost:6379
